### ISSUE TITLE
DataTables Warning when paste something in search box

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#10]
During test session, I've do the following:
1. Write something in Services -> Host Name search box.
2. In this search box, I do CTRL-A and CTRL-X to cut string,
3. Then CTRL-V in main search box.

And I have the following warning:

![align_datatables_warn](https://cloud.githubusercontent.com/assets/8926922/15931739/3f19cc48-2e59-11e6-8890-7a951afde989.png)

And after I get many times this window until I remove the paste string.

**Comment by mohierf** [comment]
Fixed.
