### ISSUE TITLE
Number of services CRITICAL seems wrong

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#104]
Compared to Alignak-app, it seems that the number of `CRITICAL` services is not the same as that of the WebUI.

Alignak-app shows 2 more than Webui...

**Comment by algorys** [comment]
This problem seems to no longer appear... 

However, the last time there were one hosts in `acknowledged` and one in `downtime`. 

Maybe the differences came from there?

**Comment by mohierf** [comment]
Fixed
