### ISSUE TITLE
Improvements for connection to WebUI

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#107]
In this issue, there is two ideas but I think they are related:

1. If WebUI can remember the name of the user and/or the password, I think it will be usefull. With a check box `remember me` or something like that.

2. Another thing is that, if WebUI can remember this, when Alignak-app link to WebUI pages, it'll display it directly and do not need again to login. We can also imagine that some business have link to WebUI in some document, Wikis, etc...

**Comment by mohierf** [comment]
Related with https://github.com/Alignak-monitoring-contrib/alignak-app/issues/74. Once the alignak-app user got logged-in, a backend token is available in alignak-app and it can be provided to the WebUI as a credentials information to avoid the login step ... the alignak-app can POST on the `/login` WebUI endpoint with a `username` parameter containing the backend token ... and it should be logged-in and redirected to the WebUI home page.

**Comment by mohierf** [comment]
Is this ok @algorys ?

**Comment by algorys** [comment]
Yes. I'll implémentation that.
