### ISSUE TITLE
Minor Enhancement: Display of link in Services and Livestate

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#11]
On Services and Livestate page, if you select a service or a host, link are not very apparent (blue on blue). The same appears when mouse is over.

![align_link](https://cloud.githubusercontent.com/assets/8926922/15933571/8783e160-2e60-11e6-91d5-b6aae5d0010b.png)

Maybe choose a color like on link in Hosts page.

**Comment by mohierf** [comment]
I changed the background color ... and made a few cleaning in the table layout.
