### ISSUE TITLE
Session limit

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-webui#110]
The session closed after few time, and in our supervision center, on big monitors, it's not good :p

**Comment by mohierf** [comment]
Your "supervision center" or your "monitoring center" ... LOL

Currently the WebUI's session manager has a time limit of one hour after the first connection ... this timer should be restarted as soon as an action takes place and the user will not be disconnected if he has some ongoing actions.

 Moreover, we should have an unlimited session on the one-eye view ... this to allow having a full screen without any user action needed!

**Comment by mohierf** [comment]
The session manager may be easily configured for an unlimited session duration. the session will expire only when the user will close its browser
