### ISSUE TITLE
Downtime trigger 500 error on requested url

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#111]
When we schedule a downtime on an host, the requested url is internal error code 500:

`Sorry, the requested URL 'http://demo.alignak.net/host/passive-02' caused an error:`

**Comment by mohierf** [comment]
![image](https://cloud.githubusercontent.com/assets/2932687/21066647/034306f0-be67-11e6-8a50-98f533ce9d0d.png)


Problem is on the logcheckresult on the right side ... should not be there!

**Comment by mohierf** [comment]
Seems to be fixed because related with another problem in the backend
