### ISSUE TITLE
show XX rows (hosts+services) does not work properly

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#115]
[Broken pagination  #112](https://github.com/Alignak-monitoring-contrib/alignak-webui/issues/112)

view hosts=14 UP e.g. show 10 rows (**selection of the second page is missing**)

![20161231_webui_show_rows](https://cloud.githubusercontent.com/assets/20840532/21577142/9e4b7552-cf50-11e6-9f7b-7c580e8937fd.jpg)

**Comment by mohierf** [comment]
Same problem as #112
