### ISSUE TITLE
parents, children, notes, notes_url, action_url not work

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#117]
**Overview for host:**
parents, children, notes, notes_url, action_url not work
$HOSTADDRESS$ $HOSTNAME$ are not replaced in url's

E.g.
"action_url          action-title::description-action_url,,http://$HOSTADDRESS$"
Webbrowser URL: -> http://WEBUI:5001/host/description-action_url,,http://$HOSTADDRESS$

"action_url          action-title,,tag::description-action_url,,http://$HOSTNAME$"
Webbrowser URL: -> http://WEBUI:5001/host/description-action_url,,http://$HOSTNAME$

**Comment by mohierf** [comment]
@spea1 : a bit more explanation on this please ?

**Comment by mohierf** [comment]
I think I got it :)
