### ISSUE TITLE
Enhance 'eye view'

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-webui#118]
In eye view, I think it could better to have the field with `0` in grey to have only important thinks in color.
I mean about fields like I put in red rectangle in the screen (it's example fields to put in grey)

![test](https://cloud.githubusercontent.com/assets/239744/21589642/3eb808d0-d0f4-11e6-9324-5463d1fc0797.png)

**Comment by mohierf** [comment]
#155 refactoring
