### ISSUE TITLE
Bad link in Host page

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#12]
When you are on a page of a specific host, like: 

http://xxx.xxx.xxx.xxx/host/57553dc35eb3a122bffa1b29

If you are on `Services` tab, under **Host name**, the link to host have the following format:

http://xxx.xxx.xxx.xxx/host/host/57553dc35eb3a122bffa1b29

The url contains double `host/`.

**Comment by mohierf** [comment]
Each backend object now has its own `endpoint` and `html_link` property that create a proper link to the object page. If the object do not have its own page(eg. command) it links to the global objects page (eg. commands)
