### ISSUE TITLE
Suggestion: Replacing the overall host status image with service image

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#128]
![host-status](https://cloud.githubusercontent.com/assets/20840532/22182582/f0df6c7e-e0a8-11e6-8c5e-c8a719f79078.jpg)

**Comment by algorys** [comment]
...be discussed. 

But if we do that, maybe replace `Overall Status` by `Host Services Status` ?

**Comment by mohierf** [comment]
I find it a nice idea :+1:  and I do agree with both of you. I am not really convinced with the current display that seems not perfectly clear. Perharps replacing with *Host service status* it will make it more clear

I will make some tests with this

**Comment by spea1** [comment]
Downtime and ack remains unchanged.
Host Services Status with Service Image.
I think that's great ;)

**Comment by mohierf** [comment]
Done
