### ISSUE TITLE
Dashbord table widget improve the look. Unfortunately no use.

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#133]
Widget options does not work.

**Comment by mohierf** [comment]
Dahsboard and widgets need some refactoring ... I also noticed broken configuration and broken options when adding a new widget in the dashboard ... I am thinking of pre-built dashboards that should be stored in the alignak backend ... stay tuned

**Comment by spea1** [comment]
I agree, it has to be reworked so that a WOW effect arises.
e.g. https://almsaeedstudio.com/themes/AdminLTE/index2.html

**Comment by mohierf** [comment]
I am thinking to abandon the Add widget feature ... it is too complex to maintain. Defining a dshboard in a configuration file (or backend) wil be more appropriate

**Comment by spea1** [comment]
**Please think now as a user not as a developer :)**
1. It is easy to use.
2. Should have many options
3. And the look is supposed to inspire the people

**Comment by mohierf** [comment]
Of course :)
