### ISSUE TITLE
Some ideas for the WebUI home page...

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#146]
An idea for the WebUI home page:
**1. some figures**
![image](https://cloud.githubusercontent.com/assets/2932687/22695560/75df5976-ed4b-11e6-8064-d928d1fb86a3.png)

**2. some graphs**
![image](https://cloud.githubusercontent.com/assets/2932687/22695496/3d6350e8-ed4b-11e6-9fe2-e185fc41b2c3.png)

**3. the problems**
![image](https://cloud.githubusercontent.com/assets/2932687/22695514/4b8d333c-ed4b-11e6-8312-4387f6ce605f.png)

@spea1, @algorys, @ddurieux : What about this instead of the current dashboard?

**Comment by algorys** [comment]
@mohierf I think that's a great idea. Colors and State in letters too.

**Comment by mohierf** [comment]
The *probable* new WebUI home page:
![image](https://cloud.githubusercontent.com/assets/2932687/22942137/94230e26-f2e8-11e6-91f6-dd08c0ad5e3e.png)

![image](https://cloud.githubusercontent.com/assets/2932687/22942159/a93ace0c-f2e8-11e6-8857-67c582d64e97.png)

![image](https://cloud.githubusercontent.com/assets/2932687/22942179/bb5f0a94-f2e8-11e6-8bb8-155f43bcb86c.png)

**Comment by ddurieux** [comment]
I like the `1. some figures`, it's my reference at work on the big monitor...
+ add this important view behind could be cool

**Comment by algorys** [comment]
IMHO graphs are not necessary. Home page should just contains fast readable datas :wink:

Graphs can be display in a a Perf / Graphic view ?

`1.` with `3.` under as @ddurieux said is best.

**Comment by mohierf** [comment]
As of #155:
- Livestate view is the new home page.
- Live synthesis history graphes are available in the currently view

Both views are refactored to make them more readable
