### ISSUE TITLE
Webui: No login possible "Internal Server Error"

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#147]
**Error: "**  "comit 07f5154c0f0b70b745bbd69404570e2ff853ff58"
*Works:** "git reset --hard 025725e4ff5e8090fdf122e938539f9b1678dd96"

´´´´
*** Starting uWSGI 2.0.14 (64bit) on [Tue Feb  7 15:31:19 2017] ***
compiled with version: 5.4.0 20160609 on 19 December 2016 00:00:38
os: Linux-4.4.0-62-myHost #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017
nodename: myHost
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/alignak
*** running under screen session 21856.alignak-webui ***
writing pidfile to /tmp/alignak-webui.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setuid() to 1001
your processes number limit is 31777
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5001 fd 8
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0x172d680
[carbon] added server 127.0.0.1:2003
[carbon] carbon plugin started, 60s frequency, 3s timeout, max retries 0, retry delay 7s
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 507200 bytes (495 KB) for 4 cores
*** Operational MODE: preforking ***
Application is in production mode
Configuration read from: [u'/etc/alignak-webui/settings.cfg']
Application debug mode: False
Opening message file /usr/local/lib/python2.7/dist-packages/alignak_webui-0.6.16.3-py2.7.egg/alignak_webui/res/en_US.mo for locale en_US
Locale not found. Using default language messages (English)
Language is English (default)...
Configured log level: 20
Configured log file: /usr/local/var/log/alignak/alignak-webui.log
Logging to file: /usr/local/var/log/alignak/alignak-webui.log
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui] --------------------------------------------------------------------------------[0m
INFO:alignak_webui:--------------------------------------------------------------------------------
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui] Alignak-WebUI, version 0.6.16.3[0m
INFO:alignak_webui:Alignak-WebUI, version 0.6.16.3
[2017-02-07 15:31:19 UTC] INFO: [alignak_webui] Copyright (c) 2015-2017 - Frdric Mohier
INFO:alignak_webui:Copyright (c) 2015-2017 - FrÃ©dÃ©ric Mohier
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui] License: GNU Affero General Public License, version 3[0m
INFO:alignak_webui:License: GNU Affero General Public License, version 3
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui] --------------------------------------------------------------------------------[0m
INFO:alignak_webui:--------------------------------------------------------------------------------
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui] --------------------------------------------------------------------------------[0m
INFO:alignak_webui:--------------------------------------------------------------------------------
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui] Alignak-WebUI, listening on 127.0.0.1:5001 (debug mode: False)[0m
INFO:alignak_webui:Alignak-WebUI, listening on 127.0.0.1:5001 (debug mode: False)
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui] Alignak-WebUI, using Alignak Backend on http://127.0.0.1:5000[0m
INFO:alignak_webui:Alignak-WebUI, using Alignak Backend on http://127.0.0.1:5000
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui] Alignak-WebUI, using Alignak Web Services on http://1.2.3.4:8888[0m
INFO:alignak_webui:Alignak-WebUI, using Alignak Web Services on http://1.2.3.4:8888
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui] --------------------------------------------------------------------------------[0m
INFO:alignak_webui:--------------------------------------------------------------------------------
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui.application] Initializing application...[0m
INFO:alignak_webui.application:Initializing application...
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui.application] load plugins from: /usr/local/lib/python2.7/dist-packages/alignak_webui-0.6.16.3-py2.7.egg/alignak_webui/plugins[0m
INFO:alignak_webui.application:load plugins from: /usr/local/lib/python2.7/dist-packages/alignak_webui-0.6.16.3-py2.7.egg/alignak_webui/plugins
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui.application] trying to load plugin 'commands' ...[0m
INFO:alignak_webui.application:trying to load plugin 'commands' ...
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.commands.commands.PluginCommands'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.commands.commands.PluginCommands'>]
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui.utils.plugin] Found table 'commands_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'commands_table' for external
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui.utils.plugin] Found list '/commands/list' for command[0m
INFO:alignak_webui.utils.plugin:Found list '/commands/list' for command
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui.utils.plugin] Plugin Commands is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Commands is installed and enabled.
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui.application] registered plugin 'commands'[0m
INFO:alignak_webui.application:registered plugin 'commands'
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui.application] trying to load plugin 'users' ...[0m
INFO:alignak_webui.application:trying to load plugin 'users' ...
[92m[2017-02-07 15:31:19 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.users.users.PluginUsers'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.users.users.PluginUsers'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'information' for user[0m
INFO:alignak_webui.utils.plugin:Found widget 'information' for user
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found table 'users_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'users_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found list '/users/list' for user[0m
INFO:alignak_webui.utils.plugin:Found list '/users/list' for user
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Users is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Users is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'users'[0m
INFO:alignak_webui.application:registered plugin 'users'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'timeperiods' ...[0m
INFO:alignak_webui.application:trying to load plugin 'timeperiods' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.timeperiods.timeperiods.PluginTimeperiods'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.timeperiods.timeperiods.PluginTimeperiods'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found table 'timeperiods_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'timeperiods_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found list '/timeperiods/list' for timeperiod[0m
INFO:alignak_webui.utils.plugin:Found list '/timeperiods/list' for timeperiod
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Timeperiods is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Timeperiods is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'timeperiods'[0m
INFO:alignak_webui.application:registered plugin 'timeperiods'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'servicedependencies' ...[0m
INFO:alignak_webui.application:trying to load plugin 'servicedependencies' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.servicedependencies.servicedependencies.PluginServicesDependencies'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.servicedependencies.servicedependencies.PluginServicesDependencies'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found table 'servicedependencys_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'servicedependencys_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found list '/servicedependencys/list' for servicedependency[0m
INFO:alignak_webui.utils.plugin:Found list '/servicedependencys/list' for servicedependency
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Services dependencies is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Services dependencies is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'servicedependencies'[0m
INFO:alignak_webui.application:registered plugin 'servicedependencies'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'servicegroups' ...[0m
INFO:alignak_webui.application:trying to load plugin 'servicegroups' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.servicegroups.servicegroups.PluginServicesGroups'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.servicegroups.servicegroups.PluginServicesGroups'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found list '/servicegroups/list' for servicegroup[0m
INFO:alignak_webui.utils.plugin:Found list '/servicegroups/list' for servicegroup
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found table 'servicegroups_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'servicegroups_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Services groups is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Services groups is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'servicegroups'[0m
INFO:alignak_webui.application:registered plugin 'servicegroups'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'hostgroups' ...[0m
INFO:alignak_webui.application:trying to load plugin 'hostgroups' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.hostgroups.hostgroups.PluginHostsGroups'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.hostgroups.hostgroups.PluginHostsGroups'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found table 'hostgroups_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'hostgroups_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found list '/hostgroups/list' for hostgroup[0m
INFO:alignak_webui.utils.plugin:Found list '/hostgroups/list' for hostgroup
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Hosts groups is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Hosts groups is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'hostgroups'[0m
INFO:alignak_webui.application:registered plugin 'hostgroups'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'realms' ...[0m
INFO:alignak_webui.application:trying to load plugin 'realms' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.realms.realms.PluginRealms'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.realms.realms.PluginRealms'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found list '/realms/list' for realm[0m
INFO:alignak_webui.utils.plugin:Found list '/realms/list' for realm
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found table 'realms_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'realms_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Realms is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Realms is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'realms'[0m
INFO:alignak_webui.application:registered plugin 'realms'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'logcheckresults' ...[0m
INFO:alignak_webui.application:trying to load plugin 'logcheckresults' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.logcheckresults.logcheckresults.PluginLogCheckResults'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.logcheckresults.logcheckresults.PluginLogCheckResults'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found table 'logcheckresults_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'logcheckresults_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found list '/logcheckresults/list' for logcheckresult[0m
INFO:alignak_webui.utils.plugin:Found list '/logcheckresults/list' for logcheckresult
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Log check results is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Log check results is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'logcheckresults'[0m
INFO:alignak_webui.application:registered plugin 'logcheckresults'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'lookup' ...[0m
INFO:alignak_webui.application:trying to load plugin 'lookup' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.lookup.lookup.PluginLookup'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.lookup.lookup.PluginLookup'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Dashboard is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Dashboard is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'lookup'[0m
INFO:alignak_webui.application:registered plugin 'lookup'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'histories' ...[0m
INFO:alignak_webui.application:trying to load plugin 'histories' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.histories.histories.PluginHistorys'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.histories.histories.PluginHistorys'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found table 'historys_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'historys_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found list '/historys/list' for history[0m
INFO:alignak_webui.utils.plugin:Found list '/historys/list' for history
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Histories is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Histories is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'histories'[0m
INFO:alignak_webui.application:registered plugin 'histories'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'userrestrictroles' ...[0m
INFO:alignak_webui.application:trying to load plugin 'userrestrictroles' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.userrestrictroles.userrestrictroles.PluginUserRestrictRoles'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.userrestrictroles.userrestrictroles.PluginUserRestrictRoles'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found table 'userrestrictroles_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'userrestrictroles_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found list '/userrestrictroles/list' for userrestrictrole[0m
INFO:alignak_webui.utils.plugin:Found list '/userrestrictroles/list' for userrestrictrole
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin User restrict roles is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin User restrict roles is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'userrestrictroles'[0m
INFO:alignak_webui.application:registered plugin 'userrestrictroles'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'worldmap' ...[0m
INFO:alignak_webui.application:trying to load plugin 'worldmap' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.worldmap.worldmap.PluginWorldmap'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.worldmap.worldmap.PluginWorldmap'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'worldmap' for external[0m
INFO:alignak_webui.utils.plugin:Found widget 'worldmap' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'worldmap' for dashboard[0m
INFO:alignak_webui.utils.plugin:Found widget 'worldmap' for dashboard
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Worldmap is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Worldmap is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'worldmap'[0m
INFO:alignak_webui.application:registered plugin 'worldmap'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'hosts' ...[0m
INFO:alignak_webui.application:trying to load plugin 'hosts' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.hosts.hosts.PluginHosts'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.hosts.hosts.PluginHosts'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found list '/hosts/list' for host[0m
INFO:alignak_webui.utils.plugin:Found list '/hosts/list' for host
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'information' for host[0m
INFO:alignak_webui.utils.plugin:Found widget 'information' for host
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'configuration' for host[0m
INFO:alignak_webui.utils.plugin:Found widget 'configuration' for host
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'location' for host[0m
INFO:alignak_webui.utils.plugin:Found widget 'location' for host
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'services' for host[0m
INFO:alignak_webui.utils.plugin:Found widget 'services' for host
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'metrics' for host[0m
INFO:alignak_webui.utils.plugin:Found widget 'metrics' for host
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'timeline' for host[0m
INFO:alignak_webui.utils.plugin:Found widget 'timeline' for host
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'history' for host[0m
INFO:alignak_webui.utils.plugin:Found widget 'history' for host
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'events' for host[0m
INFO:alignak_webui.utils.plugin:Found widget 'events' for host
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'grafana' for host[0m
INFO:alignak_webui.utils.plugin:Found widget 'grafana' for host
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found table 'hosts_table' for external[0m
INFO:alignak_webui.utils.plugin:Found table 'hosts_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'hosts_table' for external[0m
INFO:alignak_webui.utils.plugin:Found widget 'hosts_table' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'hosts_table' for dashboard[0m
INFO:alignak_webui.utils.plugin:Found widget 'hosts_table' for dashboard
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'hosts_chart' for external[0m
INFO:alignak_webui.utils.plugin:Found widget 'hosts_chart' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'hosts_chart' for dashboard[0m
INFO:alignak_webui.utils.plugin:Found widget 'hosts_chart' for dashboard
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Hosts is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Hosts is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'hosts'[0m
INFO:alignak_webui.application:registered plugin 'hosts'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'actions' ...[0m
INFO:alignak_webui.application:trying to load plugin 'actions' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.actions.actions.PluginActions'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.actions.actions.PluginActions'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Actions is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Actions is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'actions'[0m
INFO:alignak_webui.application:registered plugin 'actions'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'minemap' ...[0m
INFO:alignak_webui.application:trying to load plugin 'minemap' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.minemap.minemap.PluginMinemap'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.minemap.minemap.PluginMinemap'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Minemap is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Minemap is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'minemap'[0m
INFO:alignak_webui.application:registered plugin 'minemap'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'dashboard' ...[0m
INFO:alignak_webui.application:trying to load plugin 'dashboard' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.dashboard.dashboard.PluginDashboard'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.dashboard.dashboard.PluginDashboard'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Dashboard is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Dashboard is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'dashboard'[0m
INFO:alignak_webui.application:registered plugin 'dashboard'
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] trying to load plugin 'alignak' ...[0m
INFO:alignak_webui.application:trying to load plugin 'alignak' ...
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] Found plugins classes: [<class 'alignak_webui.plugins.alignak.alignak.PluginAlignak'>][0m
INFO:alignak_webui.application:Found plugins classes: [<class 'alignak_webui.plugins.alignak.alignak.PluginAlignak'>]
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'alignak_table_widget' for external[0m
INFO:alignak_webui.utils.plugin:Found widget 'alignak_table_widget' for external
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Found widget 'alignak_table_widget' for dashboard[0m
INFO:alignak_webui.utils.plugin:Found widget 'alignak_table_widget' for dashboard
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.utils.plugin] Plugin Alignak is installed and enabled.[0m
INFO:alignak_webui.utils.plugin:Plugin Alignak is installed and enabled.
[92m[2017-02-07 15:31:20 UTC] INFO: [alignak_webui.application] registered plugin 'alignak'[0m
INFO:alignak_webui.application:registered plugin 'alignak'
--- no python application found, check your startup logs for errors ---
--- no python application found, check your startup logs for errors ---

´´´

**Comment by mohierf** [comment]
Thanks for reporting @spea1 I reproduce the problem, so it is almost fixed 😉

**Comment by mohierf** [comment]
Ok I reproduce ... but I do not understand why this happens 😥

**Comment by mohierf** [comment]
When starting the WebUI without uWSGI (eg. `alignak-webui` or `python app.py`) there is no problem. The problem occurs when the WebUI is started by the uWSGI server only 😕
