### ISSUE TITLE
Improvement idea : bottom scrollbar

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#15]
Bottom scrollbar may just slide each Tables (Hosts, Services,...) and keep left menu visible by user.

Or just reduce it on the head of window ?

Otherwise we'll lost menu and shortcut for the different panel.

**Comment by mohierf** [comment]
We must choose a common layout for the tables display. Currently I implemented two possible solutions.

*_First solution: *_
The tables may be responsive and display only the visible columns. Currently there is a little problem and, as you can see on the hosts and services table, the search fields do not hide ! This issue will be fixed soon in the jQuery Datatables plugin ... so I wait for this.
![image](https://cloud.githubusercontent.com/assets/2932687/16071755/5aa939fc-32dd-11e6-9645-564cf8bd8255.png)

*_Second solution: *_
The livestate table is not responsive and there is an horizontal scroll bar that allows to view the table columns.
![image](https://cloud.githubusercontent.com/assets/2932687/16071740/4a52ee2c-32dd-11e6-924e-c5757d227e9a.png)

In both solution, the visible columns may be choosed by the end user and this choice is stored in the user's preferences. 

I do agree that with the second solution the sidebar menu should remain visible ... whether it is fixed on the left side or moved to the upper bar (as when you reduce the viewport width).

On my own I prefer the second solution: responsive tables. I find this layout more user friendly .... what do you think about it ?

**Comment by algorys** [comment]
> In both solution, the visible columns may be choosed by the end user and this choice is stored in the user's preferences.

Yes I think it's essential.

Second solution is better. Like that, menu can be always accessible.

**Comment by mohierf** [comment]
Related to #74
