### ISSUE TITLE
Popup overall states bad display

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#157]
I notice that, when refresh, popup is "stuck" or "moved" down. 

This is not every time but often when we have clicked on and the refresh appears just after.

![popup_webui](https://cloud.githubusercontent.com/assets/8926922/23126499/20482368-f777-11e6-958b-162828b24f0a.png)
 
Sometimes, twice (services and hosts) are overlaps...

**Comment by mohierf** [comment]
Once the popup are clicked, they are somehow pinned by Bootstrap and if the refresh happen during this time, the popup remain stuck ... I have no fixes for this 😞
