### ISSUE TITLE
Darken the WebUI layout

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#160]
When displayed on wide screens, the current layout looks somehow pale ...

The WebUI layout is based upon the Bootstrap Material Design project: https://github.com/FezVrasta/bootstrap-material-design. This project allows to configure and build the application CSS thanks to LESS ...

**Comment by mohierf** [comment]
As suggested by @spea1:
![image](https://cloud.githubusercontent.com/assets/2932687/23245207/2504d318-f98b-11e6-93f8-d7485f4cb290.png)

**Comment by mohierf** [comment]
An idea:
![image](https://cloud.githubusercontent.com/assets/2932687/23247014/d2c6f4fc-f997-11e6-8ea7-0f25417f6ad5.png)

![image](https://cloud.githubusercontent.com/assets/2932687/23247004/c2fae2e0-f997-11e6-9731-b90a0e53c739.png)

**Comment by mohierf** [comment]
Another:
![image](https://cloud.githubusercontent.com/assets/2932687/23246941/6d11d258-f997-11e6-9801-06b872f12e63.png)

![image](https://cloud.githubusercontent.com/assets/2932687/23246977/a0f81f50-f997-11e6-9665-4c9d8598b0c7.png)

**Comment by mohierf** [comment]
Yet another:
![image](https://cloud.githubusercontent.com/assets/2932687/23247838/902addb6-f99c-11e6-8b85-b5d22d934f5d.png)
![image](https://cloud.githubusercontent.com/assets/2932687/23247844/9c514990-f99c-11e6-8fdf-e9bcc0ce79c4.png)

**Comment by mohierf** [comment]
Another again:
![image](https://cloud.githubusercontent.com/assets/2932687/23247876/ccb4fdac-f99c-11e6-8f0b-3292b323fbb4.png)

![image](https://cloud.githubusercontent.com/assets/2932687/23247862/b9a2585e-f99c-11e6-935c-2f6993906c8b.png)

**Comment by mohierf** [comment]
What I think about those examples:

- blue based layout is according to Alignak logo colors, but grey based looks better
- according panels heading with top bar is a must
- panels are white backgrounded but a discrete grey background should be nice
- using a **strong** and colored font in the panels heading is quite ugly...

**Comment by spea1** [comment]
It looks awesome. Unfortunately blue is used as status color.

**Comment by mohierf** [comment]
The result may be:
![image](https://cloud.githubusercontent.com/assets/2932687/23250732/ad2a0b7c-f9aa-11e6-97fd-9672d3216c1f.png)

![image](https://cloud.githubusercontent.com/assets/2932687/23250970/a1dcb8cc-f9ab-11e6-9edc-a20df594bcf5.png)

**Comment by ddurieux** [comment]
For livestate, agree to put it in white the title, but change the icon to something like this http://fontawesome.io/icon/exclamation-circle/ to have something (the icon) different

**Comment by mohierf** [comment]
Why replacing the current icon? The heartbeat icon seems more appropriate to indicate that it is the system live state, no?

**Comment by ddurieux** [comment]
to display the livestate is OK, but when livestate is not OK perhaps put another icon instead use color to be different

**Comment by mohierf** [comment]
Why not? I will give a try ... but I am not convinced it is the best solution. In the livestate tabbed view I am adding this icon in the tab title when there is a problem: http://fontawesome.io/icon/bolt/

**Comment by ddurieux** [comment]
Ok for the Flash logo :D

**Comment by mohierf** [comment]
The last version:
- white stoing text
- count hosts / services problems
- indicate the worst state with the number of `bolt` icons

![image](https://cloud.githubusercontent.com/assets/2932687/23254013/d417e662-f9b6-11e6-8105-fd032cf12af0.png)

**Comment by spea1** [comment]
"Last state changed"?
 I have only problem with "Since ", for sreenshots in the error case timestemp is very important to me.

**Comment by mohierf** [comment]
Login page:
![image](https://cloud.githubusercontent.com/assets/2932687/23255769/19ac5af4-f9bd-11e6-9e8a-dc7459b4a7c9.png)

**Comment by mohierf** [comment]
Livestate including last state changed **and** date:

![image](https://cloud.githubusercontent.com/assets/2932687/23256372/6afa3a14-f9bf-11e6-84dd-353ec04f7c5f.png)

**Comment by spea1** [comment]
Is the world beautiful :dancing_men:
