### ISSUE TITLE
Display in Webui the "Last state changed" as web browser time for hosts and services

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#165]

**Comment by mohierf** [comment]
Are you meaning to use the local browser time format for displaying this information?

**Comment by spea1** [comment]
Yes, like "last check"

**Comment by mohierf** [comment]
An example please?

**Comment by spea1** [comment]
E.g. In the host table
![webui-20170222](https://cloud.githubusercontent.com/assets/20840532/23208012/b2d3700c-f8f3-11e6-8ae5-c3aba12f06c7.jpg)

**Comment by mohierf** [comment]
Ok. As a quick workaround, you can update the *plugins/host/settings.cfg* file with:
```
[table.ls_last_state_changed]
type=datetime
title=Last state changed
editable=False
```

This will change the timestamp to a date/time format 😉 and I will chage this as default in a next version
