### ISSUE TITLE
Add for hosts and services "Status" & "Overall status" in table view option "any" or "*"

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#166]
![add-any](https://cloud.githubusercontent.com/assets/20840532/23169093/bb950628-f84a-11e6-87b9-e2a54938c946.jpg)

**Comment by mohierf** [comment]
To have "any" value in a column, you must remove the filter. For this, click on the filter and hit the backspace or delete key on the keyboard

**Comment by spea1** [comment]
It is not so easy to remove the filter :(

**Comment by mohierf** [comment]
I do agree ... and I will look for a more simple solution. You can also reset all the filters with one of the topbar buttons:
![image](https://cloud.githubusercontent.com/assets/2932687/23208455/5a57d9de-f8f5-11e6-8b38-22c0e18aad93.png)

Use the button with the red bar sign

**Comment by spea1** [comment]
The removal of the filters is very difficult.
Need option "any" or "*"
![status](https://cloud.githubusercontent.com/assets/20840532/23216388/12120ab6-f916-11e6-952b-2a47a3173058.jpg)
