### ISSUE TITLE
Log table: "Last state changed" in  and search host

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#170]
- "Last state changed" in Log table is "Never dated!"
- Host search works but Name and data in the table is not displayed

![log-table](https://cloud.githubusercontent.com/assets/20840532/23210612/af18de24-f8fe-11e6-824e-e1b784368a88.jpg)

**Comment by mohierf** [comment]
**1.** I will have a look to this ... a settings problem anyway :/

**2.** Last state changed is "Never dated" when the value is 0, which means that this value is not known (eg. state never changed...) or it has not been stored in the backend by Alignak :/

**Comment by mohierf** [comment]
Fixed
