### ISSUE TITLE
Error popups on Dashboard view

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#184]
![image](https://cloud.githubusercontent.com/assets/2932687/23306055/d474dcc8-faa1-11e6-86bd-7ddd5b191e7a.png)

Those popup are nothing to care of ... they appear when navigating from the dashboard view to another page whereas the dahboard is loading its widgets ...

**Comment by spea1** [comment]
Please use all over in webui event time or "Last state changed"
