### ISSUE TITLE
Timeline tab of an host: logcheckresult format

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#186]
![image](https://cloud.githubusercontent.com/assets/2932687/23306970/05e65c10-faa6-11e6-8cc9-3c2ae50a2816.png)

The log check result formatting is not correct ...

**Comment by spea1** [comment]
Please use all over in webui event time or "Last state changed"

**Comment by mohierf** [comment]
Fixed with #250
