### ISSUE TITLE
Problems synthesis icons

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#188]
Instead of:
![image](https://cloud.githubusercontent.com/assets/2932687/23308340/31a21a1a-faab-11e6-9e6f-4378093f53bf.png)

we should have:
![image](https://cloud.githubusercontent.com/assets/2932687/23308326/26aaa776-faab-11e6-9aba-8e7be5116d60.png)

or even this:
![image](https://cloud.githubusercontent.com/assets/2932687/23308408/56926172-faab-11e6-8c16-7817fde84691.png)

**Note**: changed the icon / labels opacity!

**Comment by ddurieux** [comment]
the third

**Comment by algorys** [comment]
I suggest something like that:

![webui_resume](https://cloud.githubusercontent.com/assets/8926922/23308862/defea740-faac-11e6-825a-f6e6a6b60146.png)

I think it's more readable that icon over others.

**Comment by mohierf** [comment]
The problem with this solution may be on low resolution screens ... 
![image](https://cloud.githubusercontent.com/assets/2932687/23309087/a8723cb8-faad-11e6-8e84-1f6ed1e5ec61.png)

Why not one of those:
![image](https://cloud.githubusercontent.com/assets/2932687/23309429/eb5891d4-faae-11e6-8961-16f7c1638114.png)

**Comment by algorys** [comment]
On second, the first one seems good:

Number below and problems above :+1:

**Comment by mohierf** [comment]
This is also my preferred one 😉

**Comment by mohierf** [comment]
It should look like this:
![image](https://cloud.githubusercontent.com/assets/2932687/23309749/39797832-fab0-11e6-9533-586eb057034a.png)

or this:
![image](https://cloud.githubusercontent.com/assets/2932687/23310100/9a196ea8-fab1-11e6-8f8c-fcebd5b3e289.png)

**Comment by mohierf** [comment]
The last one is really clean and sexy 😉 
![image](https://cloud.githubusercontent.com/assets/2932687/23310156/ce6ff71c-fab1-11e6-8a60-e4244655c061.png)

**Comment by algorys** [comment]
yes more clearer like that :hammer:

**Comment by mohierf** [comment]
With exactly the same color codes as the other elements:
![image](https://cloud.githubusercontent.com/assets/2932687/23310469/f02014ae-fab2-11e6-9a42-b5f3905d9630.png)

I will push and merge this one 😉

**Comment by mohierf** [comment]
With some explanations for you @spea1 😉 

Base row is the total of 13 hosts and 210 services, 223 monitored items.
2 hosts are in problem (not UP and not ACK nor DOWNTIME)
9 services are in problem (idem)
11 total problems

**Comment by spea1** [comment]
I can not open the tables view with filter for count (total and problems)!
The link [+ ???] was not bad to open the tabelen view (any).
Use the icon as link for [+ ???]
Horizontally there is a lot of space :)
I would say broad not high.

**Comment by mohierf** [comment]
Related with https://github.com/Alignak-monitoring-contrib/alignak-webui/issues/93

**Comment by spea1** [comment]
Why should I not see with one click the Problem?
