### ISSUE TITLE
Currently view: improvements and ideas

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#199]
As of today:
![image](https://cloud.githubusercontent.com/assets/2932687/23379737/5b0902d0-fd38-11e6-90da-6cad6537d31c.png)

As largely commented here: https://github.com/shinken-monitoring/mod-webui/issues/440, come great and nice ideas.

**Comment by spea1** [comment]
I find counts with description better.
Full screen mode is a view for which no mouse is used when it is (e.g. 4m) away.
My proposition makes all counter in a frame one for host one for services.
There will be plenty of room for description or symbols.
![the-eye](https://cloud.githubusercontent.com/assets/20840532/23380358/bd5fe65e-fd3a-11e6-909b-0a7009c9642e.jpg)

**Comment by mohierf** [comment]
Nice idea to make only one panel for all hosts count and percentage 👍 

![image](https://cloud.githubusercontent.com/assets/2932687/23391994/2b1ecc9e-fd79-11e6-8c03-d5ee7a44605b.png)

**Comment by mohierf** [comment]
This PR https://github.com/Alignak-monitoring-contrib/alignak-webui/pull/202 builds a view with one panel for hosts count and percentage, and one panel for services count and percentage. 

Let us give a try ... and some feedback 😉

**Comment by algorys** [comment]
:+1: but with a little more text on panels :wink: (just percentages make it strange....)

**Comment by mohierf** [comment]
Thanks to #202 the panels in this view are configurable in the application *settings.cfg* file. As such, they can be adapted to each one's needs ...
