### ISSUE TITLE
Worldmap widget: height

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#200]
Free space to take full advantage.
The height from Worldmap widget, not match to the minimum "Host or Services chart widget" height.

![height](https://cloud.githubusercontent.com/assets/20840532/23383145/4c3aec2a-fd45-11e6-8f62-a9a5c971e423.jpg)

**Comment by mohierf** [comment]
Temporarily disabled, see #212

**Comment by mohierf** [comment]
Modification described in #212
