### ISSUE TITLE
Timeline pagination

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-webui#21]
The pagination is not very good for this type of display/view.

We could go in end of page/timeline and webui load the _next page_ and display the page 2 at the end, like this, we have a continuous timeline.

As example, the google image search, it load the next page/section when we are on end of previous page/section

**Comment by mohierf** [comment]
Nice idea ...

**Comment by mohierf** [comment]
Infinite scroll is available on this page now
