### ISSUE TITLE
Bad display of Menus in reduced Windows

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#26]
Hello,

On reduced windows, there is a display problem of left menu. This one who's call Global Elements.

It seems appears on Chrome (Ubuntu 16.24 LTS), Android (Chrome) and Firefox (Ubuntu too).

![capture du 2016-07-02 21-03-52](https://cloud.githubusercontent.com/assets/8926922/16542062/e52a34dc-4098-11e6-93f4-013985ce5426.png)

The bouton is over the other menu. And if we click on it, it display some information about user:

![capture du 2016-07-02 21-22-10](https://cloud.githubusercontent.com/assets/8926922/16542100/18630a66-409b-11e6-87b4-16b4f85faa88.png)

I don't know if it was tests or not.

**Comment by mohierf** [comment]
Global elements is only a debug information ... I left this information for some testings purpose for @ddurieux

**Comment by algorys** [comment]
ok :)
