### ISSUE TITLE
Tables: long item breaks table layout

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#27]
![image](https://cloud.githubusercontent.com/assets/2932687/16553290/07d19ba8-41c8-11e6-956c-2e628eea8288.png)

Solutions:
1/ shorten the diaplyed text
2/ use text ellipsis

**Comment by ddurieux** [comment]
Perhaps display only _output_ and when mouse is on the output text, display a tooltip with the long output. If I remember, we can't have _longoutput_ without _output_

**Comment by mohierf** [comment]
Fixed with the default table layout that can be configured in the plugins settings configuration file
