### ISSUE TITLE
Deactivate the autorefresh in edition menu

### ISSUE THREAD

**Issue by fpeyre** [Alignak-monitoring-contrib/alignak-webui#277]
When I want edit an existing host, or add a service to an host in the webui, the autorefresh (when make a refresh) cancel all my current modification. 

It should be deactivated when we are in edition menu.
The version of the webui is  0.8.3.4

To reproduce:
* Activate the edition mode
* Go to an host page
* Select edit the host or declare a new service
* Type something in a field
* Wait the refresh

**Comment by mohierf** [comment]
I agree with this 👍

**Comment by mohierf** [comment]
Fixed with #278
