### ISSUE TITLE
Grafana services view stuck to "Fetching Data..."

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#281]
WebUI display the Grafana in Host view but inside the Service view grafana tab is stuck on Fetching Data...

**Config:**

Ubuntu 16.04

```bash
alignak==0.2 (current develop)
alignak-backend==0.8.17
alignak-backend-client==0.9.0
alignak-backend-import==0.9.0
alignak-module-backend==0.5.0
alignak-module-logs==0.5.1
alignak-notifications==0.3.1
alignak-webui==0.8.3.4
```

The WebUI logs display no errors, but in browser console I've the following:

![webui_service_grafana](https://cloud.githubusercontent.com/assets/8926922/25938117/7ab02c42-362e-11e7-9531-c3de184216c8.png)

On Host view there is no error in console.

**Comment by mohierf** [comment]
Should be fixed with the most recent version
