### ISSUE TITLE
Multi line plugin output

### ISSUE THREAD

**Issue by fjvt** [Alignak-monitoring-contrib/alignak-webui#282]
When a plugin outputs multple lines 

OK : check failed
------------------------ SESSION LOG --------------------------
[0.0413] [  DEBUG  ] [      config      ] [     <module>     ] PRD Config file config.prd.ini succesfully read.
[0.9007] [  DEBUG  ] [      plugin      ] [     resolve      ] Executing DNS lookup for somehost

This gets show in the webui in 1 line 

In other monitoring product (ninja) i had the same issue and added < pre >< /pre > tags for the long output.

Did the same in alignak and the output in gui is ok BUT the width causes part of the output to be outside of the frame it is in

**Comment by mohierf** [comment]
@fjvt : you can paste a screeshot here in a comment 😉

**Comment by mohierf** [comment]
With a small fix, rendering may be this:
![image](https://cloud.githubusercontent.com/assets/2932687/26032386/b2d6c1f6-3892-11e7-9852-8771703f87ef.png)

**Comment by fjvt** [comment]
To be tested ...
