### ISSUE TITLE
Error on influxDB backend view

### ISSUE THREAD

**Issue by fpeyre** [Alignak-monitoring-contrib/alignak-webui#286]
I use webUI  0.8.6.0.

I use InfluxDB as TSDB.

When I go to the backend menu and I click on influxDB backend, i have the following error
```
DataTables warning: table id=tbl_influxdbs_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```
![influx_pb](https://user-images.githubusercontent.com/6442706/26988553-e9f02a70-4d1d-11e7-94fd-a9944b68694c.png)

**Comment by mohierf** [comment]
Hmm... something fuzzy in the configuration of the WebUI plugin.

Would you please export your influxdb configuration from the backend with alignak-backend-cli and copy the json for I make a test?

**Comment by mohierf** [comment]
I made more tests for this and it did not happened anymore. @fpeyre please re-open if needed 😉
