### ISSUE TITLE
Realm "alias" wrong content

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#287]
````
# -----------------------------------------------------------------------------
# alignak-object-list-realms.json
# -----------------------------------------------------------------------------
_all_children               [ (0) ]
_children                   [ (0) ]
_id                         "59331807a9fb6e02ea91662e"
_level                      0
_parent                     null
_tree_parents               [ (0) ]
alias                       ""
default                     true
definition_order            100
global_critical_threshold   5
global_warning_threshold    3
hosts_critical_threshold    5
hosts_warning_threshold     3
imported_from               "unknown"
name                        "All"
notes                       ""
services_critical_threshold 5
services_warning_threshold  3
````

**Comment by mohierf** [comment]
What is wrong with this ?

**Comment by spea1** [comment]
alias  in realm is empty  https://github.com/Alignak-monitoring-contrib/alignak-backend-import/issues/77

![realm2](https://user-images.githubusercontent.com/20840532/27222792-fbe1d9d4-528d-11e7-9125-c403f7787632.jpg)

**Comment by mohierf** [comment]
Ok. If the `alias` is empty, the WebUI set its value to the `name` field ... perharps it is not a good idea to have done this ... I will change

**Comment by mohierf** [comment]
Indeed, the `alias` is used in many places in the WebUI to display a "friendly" name for the objects. If the alias is not defined, it is replaced with the object name. This is why your realm, which has no alias, looks like having one ...

I think this behavior is a quite good solution and I will make not change for this.
