### ISSUE TITLE
Alignak status: poller addres wrong value

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-webui#290]
![poller-master](https://user-images.githubusercontent.com/20840532/27252505-803d8eee-5360-11e7-9c35-7ffe3bdbd158.jpg)

**Comment by mohierf** [comment]
This information is stored in the backend by the alignak backend module. The WebUI only displays the values stored in the backend. If a problem is present it is in the alignak backend module
