### ISSUE TITLE
Add host form

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-webui#292]
In host add form, I think we can display the `address` field because not set in this form and it's something important to fill it when create the host

**Comment by mohierf** [comment]
Host address **is present** in the host creation form: 
![image](https://user-images.githubusercontent.com/2932687/27270961-244ee0b6-54c2-11e7-820e-d905b1f5c24e.png)

And ok, we should also add this field in the *New host form* ... why not
