### ISSUE TITLE
Forms to update (unification of forms)

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-webui#295]
Like creating new host form `/hosts/templates`, need fix the forms:

* `/realm/None/form` (create new realm)
* `/hostgroup/None/form` (create new hostgroup)
* `/service/None/form` (declare a new service for this host)
* `/host/windows-wmi/form` (update host template)
* `/command/None/form` (create new command)
* `/command/595a497a6085ab871a6c17d7/form` (update a command)
* `/service/None/form` (create a new service)
* `/timeperiod/None/form` (create / edit a timeperiod)
* `/user/None/form` (create / edit a user)
* `/hostdependency/None/form` (create / edit a hostdependency)
* `/grafana/None/form` (create / edit a grafana)
* `/host/595a54b26085ab871a6c180f/form` (edit a host)

**Comment by mohierf** [comment]
Why do you need this ? What is to be fixed with these forms?

**Comment by ddurieux** [comment]
To have the form right (design and bug) and to have all info, see add a grafana and you will see, miss many fields needed

**Comment by mohierf** [comment]
Fixed
