### ISSUE TITLE
Static files not seems ok

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-webui#3]
I have configurated nginx to serve static files of webui but I have 2 strange bahaviors:
- /static/logo is in reality /static/images && image load without .png but in server le file have .png extension
- /static/photos is in reality /static/images && image load without .png but in server le file have .png extension

I add my nginx configuration here as example

```
        location ~ ^/static/plugins/(.*)$ {
            alias /usr/jails/webui/root/alignak-webui/alignak_webui/plugins/$1;
            expires 1h;
        }

        location ~ ^/static/logo/(.*)$ {
            alias /usr/jails/webui/root/alignak-webui/alignak_webui/htdocs/images/$1.png;
            expires 1h;
        }

        location ~ ^/static/photos/(.*)$ {
            alias /usr/jails/webui/root/alignak-webui/alignak_webui/htdocs/images/$1.png;
            expires 1h;
        }

        location ~ ^/static/(.*)$ {
            alias /usr/jails/webui/root/alignak-webui/alignak_webui/htdocs/$1;
            expires 1h;
        }

        location / {
            client_max_body_size 20M;
            proxy_pass http://10.0.0.6:5000;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_read_timeout 120;
        }
```

**Comment by mohierf** [comment]
The `/static/logo` and `/static/photos` URL are inherited from the Shinken WebUI and should be modified ... I do agree !

Indeed, it is not a "direct" URL but a transformed one to allow the application to change the content of the image ... not that useful, I remove it !
