### ISSUE TITLE
Default Login Credentials Do Not Work

### ISSUE THREAD

**Issue by elohmrow** [Alignak-monitoring-contrib/alignak-webui#336]
`~/alignak-webui$ python test/test_web.py`
gives, among other things:
`
2905 get page /alignak
2906 ^[[36m[2017-10-12 10:46:40,986] DEBUG: [alignak_webui] before_request, url: /alignak^[[0m
2907 ^[[36m[2017-10-12 10:46:40,987] DEBUG: [alignak_webui] before_request, edition mode: False^[[0m
2908 ^[[35m[2017-10-12 10:46:40,987] WARNING: [alignak_webui] The session expired or there is no user in the session. Redirecting to the login page...^[[0m
2909 ^[[36m[2017-10-12 10:46:40,988] DEBUG: [alignak_webui] before_request, url: /logout^[[0m
2910 ^[[36m[2017-10-12 10:46:40,988] DEBUG: [alignak_webui] before_request, edition mode: False^[[0m
2911 ^[[34m[2017-10-12 10:46:40,989] INFO: [alignak_webui] Logout for current user^[[0m
2912 ^[[36m[2017-10-12 10:46:40,991] DEBUG: [alignak_webui] before_request, url: /login^[[0m
2913 ^[[36m[2017-10-12 10:46:40,991] DEBUG: [alignak_webui] before_request, edition mode: False^[[0m
2914 ^[[34m[2017-10-12 10:46:40,992] INFO: [alignak_webui] login, user 'admin' is signing in ...^[[0m
2915 ^[[36m[2017-10-12 10:46:40,992] DEBUG: [alignak_webui.webui] user_authentication, authenticating: admin^[[0m
2916 ^[[34m[2017-10-12 10:46:40,992] INFO: [alignak_webui.backend.datamanager] user_login, connection requested: admin, load: True^[[0m
2917 ^[[35m[2017-10-12 10:46:40,994] WARNING: [alignak_backend_client.client] Backend connection error, error: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /login (Caused by NewConnectionE     rror('<urllib3.connection.HTTPConnection object at 0x7f74eec70710>: Failed to establish a new connection: [Errno 111] Connection refused',))^[[0m
2918 ^[[35m[2017-10-12 10:46:40,994] WARNING: [alignak_webui.backend.backend] configured backend is not available!^[[0m
2919 ^[[34m[2017-10-12 10:46:40,994] INFO: [alignak_webui.backend.datamanager] user_login, connection message: False / Access denied! Check your username and password.^[[0m
2920 ^[[35m[2017-10-12 10:46:40,994] WARNING: [alignak_webui.webui] user authentication refused: Access denied! Check your username and password.^[[0m
2921 ^[[35m[2017-10-12 10:46:40,994] WARNING: [alignak_webui] user 'admin' access denied, message: Access denied! Check your username and password.^[[0m
`

Same from a browser (tested FF 56.0 and Safari 10.1.2):
![screen shot 2017-10-12 at 10 56 58](https://user-images.githubusercontent.com/1139586/31487856-201c7830-af3c-11e7-9f87-d580283f15ff.png)

This is my env:
`
pip list --format=columns | grep alignak
alignak                1.0.0
alignak-backend        1.0.0
alignak-backend-client 1.0.1
alignak-webui          0.9.2
`

`
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie
`

Installed from github dev repos.

please advise if you need more information

**Comment by mohierf** [comment]
Thanks for testing and reporting.

Is your Alignak backend available on localhost? The WebUI is trying to authenticate on http://127.0.0.1:5000 ...

**Comment by elohmrow** [comment]
@mohierf wow - sorry for the false alarm! i did an lsof on port 5000 - nothing.  then a ps on backend - nothing.  then i _actually started_ backend, and both those conditions reversed and i am now logged in ... i guess it makes sense, because, what i was seeing did not make sense!

thanks again!
