### ISSUE TITLE
In acknowledge form, enhance sticky description

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-webui#34]
Because not all know how sticky is used, add text after sticky:

`, if checked remove when go in OK state, otherwise on state changes`

**Comment by mohierf** [comment]
Or add an help button on the dialog that explain the external command ... it shoud be better?

**Comment by ddurieux** [comment]
perhaps, but in most cases, if I can, I explain directly in the form with little text

**Comment by mohierf** [comment]
My idea should be to have a description for each field in the data model (as we have a table column title ...) and if this description exists it can be displayed when a field help icon is hovered ...

**Comment by mohierf** [comment]
Help field is present when selecting the field in the form
