### ISSUE TITLE
Main windows icon overlap on stats

### ISSUE THREAD

**Issue by o-be-one** [Alignak-monitoring-contrib/alignak-webui#45]
Regarding the following screenshot, it's weird how icons overlaps stats ...
http://screencloud.net/v/y72o

**Comment by mohierf** [comment]
Let's come back to the basics ...

The main idea of this is to display two numbers over the icons. The first number is the 'hosts' count and the second is the 'hosts in problem' count. the icon is colored depending upon an host warning/critical threshold.

When everything is ok, we get this kind of view:
![image](https://cloud.githubusercontent.com/assets/2932687/17856057/ffde2670-687b-11e6-923f-c9788be0e830.png)

When some problems exist, we get this: 
![image](https://cloud.githubusercontent.com/assets/2932687/17858796/78e6c210-6887-11e6-9b9e-d22cc4e8750e.png)

Hosts problems are over the critical threshold (eg. red)
Services problems are below the warning threshold (eg. green)
Global problems are between the warning and critical threshold (eg. orange)

Note that currently impacts are not managed ...

On my side, I do not have any other idea for creating a view that will allow to display all those information on a more suitable manner ... any ideas to improve are welcome :wink:

**Comment by mohierf** [comment]
Closing this issue. Reopen to discuss this feature if necessary...
