### ISSUE TITLE
Unreadable map POI

### ISSUE THREAD

**Issue by o-be-one** [Alignak-monitoring-contrib/alignak-webui#47]
Regarding this : http://screencloud.net/v/cJ61
This feature is nice, but useless if we can't read it. Maybe coul be a good idea to enhance this

-----
**Edit** include screen capture into the comment:
![image](https://cloud.githubusercontent.com/assets/2932687/23606217/0e14390e-0260-11e7-94f3-329901ef3955.png)

**Comment by mohierf** [comment]
This feature is rendered thanks to a Leaflet plugin that builds clusters for the POI and that _spiderify_ the POI located in the same place. Iw ill have a look for this plugin options if we can enlarge the _spider_ when there are many hosts in the same place ...
