### ISSUE TITLE
Disabled refresh icon is not readable ; sound icon not readable when disabled

### ISSUE THREAD

**Issue by o-be-one** [Alignak-monitoring-contrib/alignak-webui#48]
http://screencloud.net/v/FnV
Maybe could be good to chose an other way to tell user that its off, and it's nice to try to use the same way to indicate it.

I think it could be nice to just fill tile's bg in grey when it's disabled, its class and discreet :), for both icons

**Comment by mohierf** [comment]
I agree that the two icons should use the same design and that this way should be the most standard one :)

Currently the standard way to disable an icon with Material design simply displays a ban sign on the icon but do not change anything else. As of it, the user is informed when he hovers the icon ... I think that I will keep the muted text to help visually understand that the feature is disabled.
