### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-webui#5]
To have a more "modern" interface, perhaps we can use material design like http://fezvrasta.github.io/bootstrap-material-design/ (it works with bootstrap web use now)

**Comment by mohierf** [comment]
You find that Bootstrap is not modern :)

My idea is rather to allow the user to choose a theme ... but once again it is not a current priority.

**Comment by mohierf** [comment]
Made a test with a material theme for Bootstrap 3:

![image](https://cloud.githubusercontent.com/assets/2932687/17019051/d94e5aca-4f3a-11e6-86ba-1497b7df2401.png)

![image](https://cloud.githubusercontent.com/assets/2932687/17019067/eb18fbe8-4f3a-11e6-8e1a-183fe92d13fb.png)

![image](https://cloud.githubusercontent.com/assets/2932687/17019085/045eaf62-4f3b-11e6-8a4b-db36b9381ac6.png)

**Comment by mohierf** [comment]
Some notes:
- page footer is displayed as a navigation bar ... it is not one!
- it reinforces my idea that a sidebar menu is not a good idea :wink:  better have a navigation bar on top of the window

**Feel free to increase this list with your comments!**

**Comment by algorys** [comment]
Apart from the color green :yum: ,

Material design seems great.

:+1: for the top menu
:+1: for choice of theme, with default as white for example.

Maybe later one theme for each user.

**Comment by mohierf** [comment]
Without material design, it is already possible to define its own theme with Bootstrap...

**Comment by mohierf** [comment]
After some few tests:
![image](https://cloud.githubusercontent.com/assets/2932687/17032128/08836578-4f78-11e6-9fd3-94fb53e3e2ec.png)

![image](https://cloud.githubusercontent.com/assets/2932687/17032140/131ade62-4f78-11e6-8d18-5296104dab9d.png)

![image](https://cloud.githubusercontent.com/assets/2932687/17032112/f86bf4fc-4f77-11e6-82f8-f6bbe869e7ac.png)

**Comment by mohierf** [comment]
This is now the default User Interface

**Comment by mohierf** [comment]
@spea1, @ddurieux, @algorys :

To avoid green/teal color on the navigation bar, we should have:
![image](https://cloud.githubusercontent.com/assets/2932687/17960774/62b32e34-6aa8-11e6-9e63-c4c482fd7e37.png)

**Comment by ddurieux** [comment]
I like it, perhaps a little too dark

**Comment by mohierf** [comment]
From @spea1: use the same color code as the one used on the user button bar:
![image](https://cloud.githubusercontent.com/assets/2932687/17963836/abef017c-6ab7-11e6-9b7f-bbdeba9289af.png)

**Comment by mohierf** [comment]
Done
