### ISSUE TITLE
Display a status for a group / dependency

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#51]
Assign a status to an elements group (eg. hosts group). This status is the worst state of all the elements in the group.

Indeed, an hosts group is a group of hosts and an host do not have any state. We have a livestate item that is linked to the host and it is this livestate item that holds the current host state. The idea behind this is to create a _fake_ group of livestate items linked to the corresponding hosts/services group.

Same feature is interesting when displaying host/service dependency

**Comment by mohierf** [comment]
Very first version of an hosts group status:

![image](https://cloud.githubusercontent.com/assets/2932687/18349904/ae8578c2-75d3-11e6-903d-21255a551672.png)

The hosts group status is computed as the worst real state of the hosts members of the group.

The real state of an host is:
- `ok` if the host is UP and all its services are OK
- `warning` if the host is UNREACHABLE or at least one of its services is WARNING
- `critical` if the host is DOWN or at least one of its services is CRITICAL
- `acknowledged` if the host is acknowledged or at least one of its services is acknowledged and no other services are WARNING or CRITICAL
- `downtime` if the host is in a scheduled downtime or at least one of its services is in a scheduled downtime and no other services are WARNING or CRITICAL

**Note:** this first version is to be improved combining the real stat of a group from the states of the dependent groups. As of it, the _All_ group should contain the worst state of all the hosts ...

**Comment by mohierf** [comment]
Lines colored depending upon the status:

![image](https://cloud.githubusercontent.com/assets/2932687/18350299/87b03ea6-75d5-11e6-96ff-85330088fbf0.png)

**Comment by algorys** [comment]
Maybe font in fields a more bold.

**Comment by mohierf** [comment]
I do agree @algorys :)

**Comment by mohierf** [comment]
Colouring the tree lines depending upon state: 
![image](https://cloud.githubusercontent.com/assets/2932687/18376328/7fcf0a1c-765e-11e6-87d4-fd3bd15c355d.png)

It is really not very nice :disappointed:

**Comment by mohierf** [comment]
Implemented in last version 0.5.2.
Closing this issue to discuss the groups trees in #92
