### ISSUE TITLE
Add route to get js and css used by webui

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-webui#65]
like /cssjs

return json with all js and css links

**Comment by mohierf** [comment]
This commit (https://github.com/Alignak-monitoring-contrib/alignak-webui/commit/70a6c8bf2fd9925c329d1ce7fade79d0fb897728) includes an external route:
- _/external/files/js_list_ route to get a JSON list of the javascript files
- _/external/files/css_list_ route to get a JSON list of the CSS files

The returned Json is formatted as is:

```
{
    "status": "ok",
    "files": ["file1", "file2", ...]
}
```

If `status` is "ok", `files" is an array of the Javascript / Css URL to use
