### ISSUE TITLE
Default WebUI layout

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#66]
Some tests for the application default layout.

**Constraints:**
- The Material Design guidelines define color palettes that are:
  ![image](https://cloud.githubusercontent.com/assets/2932687/17968857/519d6372-6acf-11e6-8cfb-492bfa661508.png)
- Some colors are, _de facto_,  excluded: green, orange, red and blue because they are used in the application to give semantics to the information
- The application logo is currently a text tranformed to an image with a transparent background. As of it this logo must be displayed on a very clear background. Currently the choice I did is to add a white background with 0.8 opacity.

**Tests**:

**1/** teal (current color)
![image](https://cloud.githubusercontent.com/assets/2932687/17968702/818457d6-6ace-11e6-8dac-e8f9bfe26cc0.png)

**2/** blue-grey-500
![image](https://cloud.githubusercontent.com/assets/2932687/17968760/d96c0656-6ace-11e6-9b92-de9d2b2bd5db.png)

**3/** grey-500
![image](https://cloud.githubusercontent.com/assets/2932687/17968806/07b6b678-6acf-11e6-8f17-6e6636b2e2ab.png)

**4/** grey-200
![image](https://cloud.githubusercontent.com/assets/2932687/17968831/2ec12938-6acf-11e6-81d1-e82a373385c5.png)

**5/** purple-400
![image](https://cloud.githubusercontent.com/assets/2932687/17968964/11572928-6ad0-11e6-9302-b39da131a9f4.png)

**6/** blue-grey-400
![image](https://cloud.githubusercontent.com/assets/2932687/17969053/71edab72-6ad0-11e6-8b9d-bde7052e7660.png)

**Comment by mohierf** [comment]
My prefered one: **6/ blue-grey-400**

What do you think about it? What is your prefered one?

@ddurieux @spea1 @Seb-Solon @algorys

**Comment by spea1** [comment]
well chosen "6/ blue-grey-400"

**Comment by mohierf** [comment]
blue-grey-400 is now the default layout
