### ISSUE TITLE
Improvement idea: NAGIOS Variable Commands

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#7]
In Commands menu, if we can have values (as memo) of the following variables. 
- $NAGIOSPLUGINSDIR$
- $PLUGINSDIR$

If I remember well, it's define in a file like `path.cfg`. I don't know if you can retrieve this an display on this board ?

Other thing in this page, columns seems not responsive on small screen. I'm not sure, it's your priority but it renderer like this:

![align_commands](https://cloud.githubusercontent.com/assets/8926922/15931172/df67c6da-2e56-11e6-9265-4267ef515db9.png)

**Comment by mohierf** [comment]
Two issues:
- the global `$NAGIOSPLUGINSDIR$` (and other global configuration variables are not available in the Alignak backend (@ddurieux ?) and, as of it, I will not be able to display them on the Web UI ...
- which browser and version are you using ? On my Chrome and Firefox, I donot have the same layout problem as yours ...

**Comment by algorys** [comment]
I use `Chrome 51.0.2704.84 (64 bit)` on `Ubuntu 16.04`.

It seems to make this only on `Commands` page. Others seems to work properly.

**Comment by mohierf** [comment]
Not the same problem for me with the last Chrome on Windows ... I will make a test with a Chrome on Ubuntu.

**Comment by ddurieux** [comment]
Yep, it's configured in alignak, so we don't have access to this. The question is: is it really essential ?

**Comment by mohierf** [comment]
I think that it would be interesting to have a dedicated page in the WebUI to browse the global Alignak configuration parameters. :+1: for this feature

**Comment by ddurieux** [comment]
We can add an API route in arbiter module to get these info

**Comment by mohierf** [comment]
Or, store those parameters in the backend to avoid creating a link between WebUI and Arbiter :-1:

**Comment by ddurieux** [comment]
Yes it's a possibility and perhaps better idea :+1:

**Comment by mohierf** [comment]
Related with #79
