### ISSUE TITLE
Business impact visualization: how many stars ?

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-webui#72]
Currently, the business impact of an element is defined as: 
- bi=0, no-importance
- bi=1, qualification
- bi=2, normal
- bi=3, production
- bi=4, important
- bi=5, top for business

The definitions are made in the `business-impacts.cfg` file shipped with the default Alignak configuration. Note that the default value of the BI is set as 2 (*normal). If one wants to focus on an element, it must increase the BI level or *use* one of the defined templates.

There are two solutions for implementing a visualisation of this business level...

One *star* per level count:
- bi=0, no-importance, 
- bi=1, qualification, ⭐️
- bi=2, normal, ⭐️⭐️
- bi=3, production, ⭐️⭐️⭐️
- bi=4, important, ⭐️⭐️⭐️⭐️
- bi=5, top for business, ⭐️⭐️⭐️⭐️⭐️ 

Only *stars* for the most important level count:
- bi=0, no-importance, 
- bi=1, qualification,
- bi=2, normal,
- bi=3, production, ⭐️
- bi=4, important, ⭐️⭐️
- bi=5, top for business, ⭐️⭐️⭐️

**Note**: this solution focuses on the most important monitored items. When some stars are displayed, it means that the item is important! It is my current preferred solution ...

**Comment by ddurieux** [comment]
I prefer One star per level count, because in solution 2 in fact you have only 4 real levels usable, not 6

**Comment by mohierf** [comment]
Indeed it is only a matter of viewing, you still have 6 usable levels (for searching, filtering,...) 😉

**Comment by spea1** [comment]
It should be visible which category an item belongs to.
But only one category can exist without stars

![star5](https://cloud.githubusercontent.com/assets/20840532/23296551/e770db28-fa75-11e6-83d3-2fc38103cdcf.jpg)

**Comment by algorys** [comment]
I'm agree with @ddurieux One star per level count is the best I think.

**Comment by mohierf** [comment]
Having one star per level count. The drawbacks of this is that all hosts will be ⭐️⭐️ and, imho, it will not make it evident to see, at a glance, which one are really important

I love the idea of @spea1 ; perharps having always only one star with an extra information is a good solution. Playing with the star color may indicate the level of importance ... I will give a try with this and copy a screen capture

**Comment by ddurieux** [comment]
With one star per level, the display say to the admin 'manage the impact of you hosts / services' to be more usable in the webui (it's my case :p)

**Comment by mohierf** [comment]
I do not agree with this reason. It should not be because we display some stars that the user will be invited to use the business impact levels... 

The UI should invite the user to set BI level by another means. As an example: if all hosts have the same business level, a popup will appear to propose setting different ones

**Comment by mohierf** [comment]
Web UI default configuration:
```
[business_impact]
; Global element to be included in the HTML and including the items and the text
;global=<span class="text-default">##items##</span><span>&nbsp;##text##</span>

; Element to be included for each BI count
;item=<span class="fa fa-trophy"></span>

; Number of elements to remove from the real business impact
; 0 is meaning that the defined item will be repeated twice for BI=2, third for BI=3
; 2 is meaning that the defined item will not be repeated for BI=2, and once for BI=3
;less=0
```

![image](https://cloud.githubusercontent.com/assets/2932687/23389467/693b9036-fd68-11e6-8624-7a98ebe52c5f.png)

Changing text color:
```
[business_impact]
; Global element to be included in the HTML and including the items and the text
;global=<span class="text-primary">##items##</span><span>&nbsp;##text##</span>

; Element to be included for each BI count
;item=<span class="fa fa-trophy"></span>

; Number of elements to remove from the real business impact
; 0 is meaning that the defined item will be repeated twice for BI=2, third for BI=3
; 2 is meaning that the defined item will not be repeated for BI=2, and once for BI=3
;less=0
```
![image](https://cloud.githubusercontent.com/assets/2932687/23379417/2aac8432-fd37-11e6-965b-82defc53d36b.png)

**And then:**
Updating *etc/settings.cfg*:
```
[business_impact]
; Global element to be included in the HTML and including the items and the text
global=<span style="color: red">##items##</span><span>&nbsp;##text##</span>

; Element to be included for each BI count
item=<span class="fa fa-beer"></span>

; Number of elements to remove from the real business impact
; 0 is meaning that the defined item will be repeated twice for BI=2, third for BI=3
; 2 is meaning that the defined item will not be repeated for BI=2, and once for BI=3
;less=0
```
![image](https://cloud.githubusercontent.com/assets/2932687/23379298/bc91584c-fd36-11e6-99e3-d24b64336c28.png)

**Another possible configuration:**
```
[business_impact]
; Global element to be included in the HTML and including the items and the text
;global=<span class="text-primary">##items##</span><span>&nbsp;##text##</span>

; Element to be included for each BI count
;item=<span class="fa fa-trophy"></span>
item=

; Unique element
unique=<div style="display: inline; font-size:0.9em;" title="##text##"><span class="fa-stack "><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-trophy fa-stack-1x fa-inverse">##bi##</i></span><span></span></div>

; Number of elements to remove from the real business impact
; 0 is meaning that the defined item will be repeated twice for BI=2, third for BI=3
; 2 is meaning that the defined item will not be repeated for BI=2, and once for BI=3
;less=0
```
![image](https://cloud.githubusercontent.com/assets/2932687/23380229/38488732-fd3a-11e6-9570-0a7ce77ac6af.png)

**And yet another one:
```
[business_impact]
; Global element to be included in the HTML and including the items and the text
;global=<span class="text-primary">##items##</span><span>&nbsp;##text##</span>

; Element to be included for each BI count
; If item is empty, then the following unique is used in place
;item=<span class="fa fa-trophy"></span>
item=

; Unique element
unique=<div style="display: inline; font-size:0.9em;" title="##text##"><span class="fa-stack"><span class="fa fa-circle fa-stack-2x"></span><span class="fa fa-stack-1x fa-inverse">##bi##</span></span></div>
level_0=

; Number of elements to remove from the real business impact
; 0 is meaning that the defined item will be repeated twice for BI=2, third for BI=3
; 2 is meaning that the defined item will not be repeated for BI=2, and once for BI=3
;less=0
```
![image](https://cloud.githubusercontent.com/assets/2932687/23380734/37be606e-fd3c-11e6-979e-174cfceb09ba.png)
