### ISSUE TITLE
Search box doesn't match anything

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#9]
If i make some research in search box in general or in Host Name, search result:

 "No matching records found"

Example in Services tab:

![align_search](https://cloud.githubusercontent.com/assets/8926922/15931508/57f76e1a-2e58-11e6-8265-789718b132c1.png)

**Comment by mohierf** [comment]
Fixed.

Default search for each column was `regex=False`. As of it it matched only if an exact value was entered in the input field. As of now, default value is `regex=True` ... which is much more interesting :wink:
