### ISSUE TITLE
Add a link to official documentation

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#95]
I think users who will encounter some problems or difficulties can have a link to the official documentation inside the WebUI. Like that if they want to know something, thay are no needed to search across the web.

Maybe inside user menu under `About` ?

**Comment by mohierf** [comment]
Page footer links to the project repository on github

About modal has a link to the project repository **and I will add a link \* to the online documentation

**Comment by algorys** [comment]
Yes :+1: great like that.
