### ISSUE TITLE
Some things are a little too small

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#96]
I do not know if this is specific to my installation (Chrome on Ubuntu 16.04, 1920x1080), or maybe it's due to theme. 

But I found WebUI display some things too small, like:
1. Police is `11px`. I think `13px` or `14px` will be better. 
2. Icons for rows, downloads, filters are too small.

If it were a bit bigger, it would gain in readability.

**Comment by mohierf** [comment]
I will enlarge the tables fonts
