### ISSUE TITLE
Icon for button download

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-webui#97]
IMHO, icon for download button (CSV, pdf, ....) is not suitable. (It's more for expand button)

Maybe an icon like [that](http://www.flaticon.com/free-icon/file_137694#term=download&page=1&position=51) will be better.

**Comment by mohierf** [comment]
On which view ?

**Comment by algorys** [comment]
On all table view:

![alig_webui_download](https://cloud.githubusercontent.com/assets/8926922/19428514/eac24424-944a-11e6-8625-7de143cccfc6.png)

**Comment by mohierf** [comment]
We must choose an icon in the font awesome icons (http://fontawesome.io/icons/) to remain consistent on all the interface :wink:

**Comment by mohierf** [comment]
We may also use the Google fonts for the material design ... because they are also embedded in the Web UI ...

**Comment by algorys** [comment]
So maybe this one http://fontawesome.io/icon/download/ instead ?

**Comment by mohierf** [comment]
+1
